sources:
  - name: venus-protocol-reserve-chapel
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/venusprotocol/venus-protocol-reserve-chapel

documents:
  - "./queries/*.graphql"
