name: Release

on:
  push:
    branches:
      - main
      - develop

jobs:
  release-smart-contracts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@v2
        with:
          node-version: 20
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn workspace @venusprotocol/keeper-bot-contracts run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.VENUS_TOOLS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: Venus Tools
          GIT_AUTHOR_EMAIL: tools@venus.io
          GIT_COMMITTER_NAME: Venus Tools
          GIT_COMMITTER_EMAIL: tools@venus.io
        run: yarn workspace @venusprotocol/keeper-bot-contracts run semantic-release
      
  release-token-converter-bot:
          runs-on: ubuntu-latest
          steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
                persist-credentials: false
      
            - uses: actions/setup-node@v2
              with:
                node-version: 20
                cache: "yarn"
      
            - name: Install dependencies
              run: yarn
      
            - name: Build
              run: yarn workspace @venusprotocol/token-converter-bot run build
      
            - name: Release
              env:
                GITHUB_TOKEN: ${{ secrets.VENUS_TOOLS_TOKEN }}
                NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                GIT_AUTHOR_NAME: Venus Tools
                GIT_AUTHOR_EMAIL: tools@venus.io
                GIT_COMMITTER_NAME: Venus Tools
                GIT_COMMITTER_EMAIL: tools@venus.io
              run: yarn workspace @venusprotocol/token-converter-bot run semantic-release
