name: Release

on:
  push:
    branches:
      - main
      - develop

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Generate subgraph types
        run: |
          yarn workspace @venusprotocol/token-converter-bot run generate-abis
          yarn workspace @venusprotocol/token-converter-bot run generate-subgraph-types

      - name: Build Keeper Bot Contracts
        run: yarn workspace @venusprotocol/keeper-bot-contracts run build

      - name: Release Keeper Bot Contracts
        if: ${{ always() }}
        env:
          GITHUB_TOKEN: ${{ secrets.VENUS_TOOLS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: Venus Tools
          GIT_AUTHOR_EMAIL: tools@venus.io
          GIT_COMMITTER_NAME: Venus Tools
          GIT_COMMITTER_EMAIL: tools@venus.io
        run: 
          yarn workspace @venusprotocol/keeper-bot-contracts run semantic-release
      
      - name: Install dependencies
        run: yarn
      
      - name: Build Token Converter Bots
        run: yarn workspace @venusprotocol/token-converter-bot run build

      - name: Release Token Converter Bot
        if: ${{ always() }}
        env:
          GITHUB_TOKEN: ${{ secrets.VENUS_TOOLS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: Venus Tools
          GIT_AUTHOR_EMAIL: tools@venus.io
          GIT_COMMITTER_NAME: Venus Tools
          GIT_COMMITTER_EMAIL: tools@venus.io
        run: yarn workspace @venusprotocol/token-converter-bot run semantic-release
      
      - name: Install dependencies
        run: yarn

      - name: Build CLI
        run: yarn workspace @venusprotocol/cli run build

      - name: Release Cli
        if: ${{ always() }}
        env:
          GITHUB_TOKEN: ${{ secrets.VENUS_TOOLS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: Venus Tools
          GIT_AUTHOR_EMAIL: tools@venus.io
          GIT_COMMITTER_NAME: Venus Tools
          GIT_COMMITTER_EMAIL: tools@venus.io
        run: yarn workspace @venusprotocol/cli run semantic-release
